### ISSUE TITLE
How does subclassing work?

### ISSUE THREAD

**Issue by munificent** [nex3/dep-import-when#2]
``` dart
abstract class Client {
  factory Client() {
    if (const bool.fromEnvironment("dart.html")) return new BrowserClient();
    return new IoClient();
  }
}
```

Using a factory constructor here means that I can no longer subclass Client, doesn't it? This breaks use cases like @jmesserly has around using this for Element where we do need to still be able to subclass. Or am I misunderstanding something?

**Comment by nex3** [comment]
You [can't currently subclass `Client` either](https://github.com/dart-lang/http/blob/master/lib/src/client.dart#L33-L36). I don't know why you'd want to anyway—it's just an interface, and doesn't have anything useful to a subclass. That's what `BaseClient` is for.

Generally I've found that it's more useful in Dart, given the way its constructor rules work, to expose an interface with a factory constructor alongside a separate mixin/subclassable class. This is the pattern that the core libraries use as well.

For the `Element` case, I actually wouldn't expect any sort of unified library like `http`, since the existing interfaces are already pretty good and wrapping is expensive. I'd expect a cross-platform library to just take `Element`; meanwhile, `html5lib` could write its own (subclassable) element class:

``` dart
import "dart:html" when dart.html;

abstract class VirtualElement implements Element {
  // ...
}
```

**Comment by jmesserly** [comment]
Nice, so it could be:

``` dart
import "dart:html" as html when dart.html;

abstract class Element implements html.Element {
  // ...
}
```

That seems fine. But how does a user use it?

``` dart
import 'package:html/html.dart';

// subclassing
class MyElement extends Element {
}

foo() {
  // Or just plain old construction:
  var e = new Element.html('<div>works server and client, cool!</div>');
}
```

**Comment by jmesserly** [comment]
In other words, I'm not seeing how this solves the problem, as other proposals do. But apologies if I'm missing it.

With the "just make dart:html importable on VM" proposal, I was planning to just have a compatible interface, using [package:html's dom](https://github.com/dart-lang/html/blob/master/lib/dom.dart) as a starting point, but with complete dart:html interfaces, and some implementations where we can.

**Comment by jmesserly** [comment]
since these bugs were closed I opened https://github.com/nex3/dep-import-when/issues/8 to continue the discussion
