### ISSUE TITLE
External libraries complexity

### ISSUE THREAD

**Issue by munificent** [nex3/dep-import-when#3]
> This proposal introduces a lot more language complexity than Configured Imports—on top of a library-choice mechanism, it also adds a notion of "external" that involves somewhat complicated scope resolutions.

I think it's worth pointing out that the team has already eaten this complexity cost. External libraries are basically the patch file mechanism we've already designed and implemented for dart2js and the VM. My intent is that, if this proposal makes progress, the existing patch files would move to use it. So, at least in theory, it should be roughly neutral in terms of _increased_ complexity.

**Comment by nex3** [comment]
Patch files are currently an implementation detail. They're not part of the language spec and they can't be used outside of the SDK, so they're not really _in the language_. You're right that implementations exist, but—and this is what I'm getting at in that sentence—making it visible to users adds complexity to the language that those users have to understand. In my view, that complexity is a much more serious cost than the implementation complexity, since it's on the order of the number of Dart users.
